# Discarded  parallel jobs because of performance
name: Build and Test

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build-test:
    runs-on: ubuntu-latest
    name: Setup, build, lint, test & coverage
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Get Node.js version from `.nvmrc` file
        id: nvmrc
        uses: browniebroke/read-nvmrc-action@v1

      - name: Install Node.js ${{steps.get_nodejs_version.outputs}}
        uses: actions/setup-node@v1
        with:
          node-version: "${{ steps.nvmrc.outputs.node_version }}"

      - name: Cache node modules
        id: cache-npm
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: npm-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            npm-

      - name: Install NPM dependencies
        run: npm install

      - name: Compile contracts
        run: npm run compile

      - name: Generate contracts TypeScript types
        run: npm run typechain

      - name: Run solhint
        run: npm run lint:sol

      - name: Run ESLint
        run: npm run lint:ts

      - name: Run unit tests
        run: npm run test:unit

      # NB: this actions yes or yes will generate a report.
      # Place it before Codecov action (it will just upload the report)
      - name: Generate & upload coverage report to Codeclimate
        continue-on-error: true
        uses: paambaati/codeclimate-action@v2.6.0
        env:
          CC_TEST_REPORTER_ID: ${{secrets.CODECLIMATE_TEST_REPORTER_ID}}
        with:
          coverageCommand: npm run coverage
          coverageLocations: ./coverage/lcov.info:lcov

      - name: Upload coverage report to Codecov
        continue-on-error: true
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage.json
          flags: unittests

      - name: Run Snyk to check for vulnerabilities
        continue-on-error: true
        uses: snyk/actions/node@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
